// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Sun May 01 14:51:18 2022

controlunit controlunit_inst
(
	.SysClock(SysClock_sig) ,	// input  SysClock_sig
	.StartStop(StartStop_sig) ,	// input  StartStop_sig
	.SW(SW_sig) ,	// input [3:0] SW_sig
	.C0(C0_sig) ,	// output  C0_sig
	.C1(C1_sig) ,	// output  C1_sig
	.C2(C2_sig) ,	// output  C2_sig
	.C3(C3_sig) ,	// output  C3_sig
	.C4(C4_sig) ,	// output  C4_sig
	.C7(C7_sig) ,	// output  C7_sig
	.C8(C8_sig) ,	// output  C8_sig
	.C9(C9_sig) ,	// output  C9_sig
	.C5(C5_sig) ,	// output  C5_sig
	.C10(C10_sig) ,	// output  C10_sig
	.C11(C11_sig) ,	// output  C11_sig
	.C12(C12_sig) ,	// output  C12_sig
	.C13(C13_sig) ,	// output  C13_sig
	.C14(C14_sig) ,	// output  C14_sig
	.SWled(SWled_sig) ,	// output [3:0] SWled_sig
	.Bled(Bled_sig) 	// output [1:0] Bled_sig
);

